udo: required
dist: trusty
language: node_js
node_js:
- '8.0'
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - skrenn99@gmail.com
cache:
  directories:
  - node_modules
install:
- npm install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run build
  on:
    branch:
    - master
addons:
  ssh_known_hosts: 207.154.228.64

after_success:
- bash "./deploy.sh"


before_install:
- openssl aes-256-cbc -K $encrypted_c4ab74e443b3_key -iv $encrypted_c4ab74e443b3_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/id_rsa
